---
name: Update python dependecies

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: 'Update dependencies'
        run: |
          python3 ./update.py ${{ github.workspace }}/git-credential-outlook.rb
          python3 ./update.py ${{ github.workspace }}/git-credential-gmail.rb
          python3 ./update.py ${{ github.workspace }}/git-credential-yahoo.rb
          python3 ./update.py ${{ github.workspace }}/git-credential-aol.rb
          python3 ./update.py ${{ github.workspace }}/git-msgraph.rb
          python3 ./update.py ${{ github.workspace }}/git-protonmail.rb
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
